### ISSUE TITLE
Add `transform-box` utilties

### ISSUE THREAD

**Issue by hacknug** [benface/tailwindcss-transforms#8]
Planning on deprecating `tailwindcss-transform` due to being under-developed and having 99% overlap with `tailwindcss-transforms`. Since yours already supports configuring all properties I don't think it makes sense to maintain both side by side.

I'd like to know if you'd be open to adding support for `transformBox`.

Here's the classes I was generating on mine:

```css
.transform-border { transform-box: border-box; }
.transform-fill { transform-box: fill-box; }
.transform-view { transform-box: view-box; }
```
